/* eslint-disable vue/no-unused-components */
/* eslint-disable vue/no-unused-components */
<template>
  <div class="mainDiv">
    <navbar />
    <div class="table">
      <table class="closed_leads">
        <tr>
          <th>
            <center>ID</center>
          </th>
          <th>
            <center>Description</center>
          </th>
          <th>
            <center>Generated by</center>
          </th>
          <th>
            <center>Count of dislikes</center>
          </th>
          <th>
            <center>Source</center>
          </th>
          <th>
            <center>Created time</center>
          </th>
          <th>
            <center>Updated time</center>
          </th>
        </tr>
        <tr
          v-for="c in getClosedLeadsServiceAgentMapGetter"
          v-bind:key="c.ticketId"
          class="lead_deets"
        >
          <td>{{ c.ticketId }}</td>
          <td>{{ c.postDesc }}</td>
          <td>{{ c.postUserId }}</td>
          <td>{{ c.countOfDislike }}</td>
          <td>{{ c.source }}</td>
          <td>{{ c.createdTime }}</td>
          <td>{{ c.updatedTime }}</td>
        </tr>
      </table>
    </div>
  </div>
</template>
<script>
import navbar from "../components/navbar.vue";
import { mapGetters } from "vuex";
export default {
  components: {
    // eslint-disable-next-line vue/no-unused-components
    navbar
  },
  created() {
    if (localStorage.getItem("accessTokenSA") == null) {
      window.location.href("http://localhost:8080/loginserviceagent");
    } else {
      this.$store.dispatch("getClosedLeadsForServiceAgent");
    }
  },
  computed: {
    ...mapGetters(["getClosedLeadsServiceAgentMapGetter"])
  }
};
</script>
<style scoped>
.closed_leads {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 88%;
  margin-top: 10%;
  margin-left: 12%;
}
.closed_leads td,
.closed_leads th {
  border: 1px solid #ddd;
  padding: 8px;
}
.closed_leads tr:nth-child(even) {
  background-color: #f2f2f2;
}
.closed_leads tr:hover {
  background-color: #ddd;
}
.closed_leads th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #444;
  color: white;
}
</style>